.TH USBIP 3 2016-02-01 "" "Linux Programmer's Manual"
.SH NAME
usbip_set_use_debug, usbip_set_use_stderr, usbip_set_use_syslog,
usbip_set_debug_flags \- USB/IP debug functions
.SH SYNOPSIS
.nf
.B #include <linux/usbip_api.h>
.sp
.BI "void usbip_set_use_debug(int val);"
.sp
.BI "void usbip_set_use_stderr(int val);"
.sp
.BI "void usbip_set_use_syslog(int val);"
.sp
.BI "void usbip_set_debug_flags(unsigned long flags);"
.sp
.ad b
.SH DESCRIPTION
These functions set debug mode to USB/IP.
.PP
.BR usbip_set_use_debug()
sets boolean value to enable debug log.
.PP
.BR usbip_set_use_stderr()
sets boolean value to enable stderr output.
.PP
.BR usbip_set_use_syslog()
sets boolean value to enable syslog output.
.PP
.BR usbip_set_debug_flags()
sets debug flags for STUB emulator for libusb.
Available when -DUSBIP_WITH_LIBUSB is used.
.PP
