.\"
.\" Copyright (C) 2016 Nobuo Iwata
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.TH USBIP 3 2016-02-01 "" "Linux Programmer's Manual"
.SH NAME
usbip_conn_init, usbip_sock_init \- USB/IP setup functions
.SH SYNOPSIS
.nf
.B #include <usbip_api.h>
.sp
.BI "void usbip_break_all_connections(void);"
.sp
.BI "void usbip_break_connection(struct usbip_sock *sock);"
.ad b
.SH DESCRIPTION
\fBusbip_break_all_connections()\fP breaks
all reading threads from USB/IP driver.
\fBusbip_break_connection()\fP breaks
reading thread specified by \fIsock\fP from USB/IP driver.
Valid when usbip_ux module is loaded otherwise they have no effect.
Netowrk connection must be closed in combination with these functions.
.SH "SEE ALSO"
.BR usbip_recv_pdu (3)
.BR usbip_attach_device (3)
.BR usbip_connect_device (3)
