.TH USBIP "8" "May 20i16" "usbip" "System Administration Utilities"
.SH NAME
usbip_ex_daemon_add \- USB/IP daemon for application side machine
.SH SYNOPSIS
.B usbip_ex_daemon_add

.SH DESCRIPTION
.B usbip_ex_daemon_app
runs in a application side machine and serves devices connected from remote machines by \fBconnect\fR command.

.SH "SEE ALSO"
\fBusbip_ex_cmd_list_local\fP\fB(8)\fB\fP
\fBusbip_ex_cmd_connect\fP\fB(8)\fB\fP
