.TH USBIP "8" "May 2016" "usbip" "System Administration Utilities"
.SH NAME
usbip_ex_cmd_unbind \- unbinds local USB device.
.SH SYNOPSIS
.B usbip_ex_cmd_unbind
<\fIbus-id\fR>

.SH DESCRIPTION
A USB/IP API example. Makes a local device not importable from remote.

.HP
\fIbus-id\fR
.IP
Bus ID of remote device to be importable.
.PP

.SH "SEE ALSO"
\fBusbip_ex_cmd_list_local\fP\fB(8)\fB\fP
\fBusbip_ex_cmd_bind\fP\fB(8)\fB\fP
