.TH USBIP "8" "May 2016" "usbip" "System Administration Utilities"
.SH NAME
usbip_ex_cmd_list_remote \- lists remote USB devices.
.SH SYNOPSIS
.B usbip_ex_cmd_list_remote
<\fIremote-addr\fR>

.SH DESCRIPTION
A USB/IP API example. Lists remote devices which are made importable on
remote.

.SH OPTIONS
.HP
\fIremote-addr\fR
.IP
IPv4 address of a remote machine.
.PP

.SH "SEE ALSO"
\fBusbip_ex_cmd_list_local\fP\fB(8)\fB\fP
\fBusbip_ex_cmd_bind\fP\fB(8)\fB\fP
