.TH USBIP "8" "May 20i16" "usbip" "System Administration Utilities"
.SH NAME
usbip_ex_daemon_dev \- USB/IP daemon for device side machine
.SH SYNOPSIS
.B usbip_ex_daemon_dev

.SH DESCRIPTION
.B usbip_ex_daemon_dev
runs in a device side machine and makes local devices accessible from a remote machine by \fBattach\fR command. The local devices should be accessible by \fBbind\fR command.

.SH "SEE ALSO"
\fBusbip_ex_cmd_list_local\fP\fB(8)\fB\fP
\fBusbip_ex_cmd_bind\fP\fB(8)\fB\fP
\fBusbip_ex_cmd_list_remote\fP\fB(8)\fB\fP
\fBusbip_ex_cmd_attach\fP\fB(8)\fB\fP
