.TH USBIP "8" "May 2016" "usbip" "System Administration Utilities"
.SH NAME
usbip_ex_cmd_connect \- connect local USB device to remote.
.SH SYNOPSIS
.B usbip_ex_cmd_connect
<\fIremote-addr\fR> <\fIbus-id\fR>

.SH DESCRIPTION
A USB/IP API example. Connects a local device to remote machine.

.SH OPTIONS
.HP
\fIremote-addr\fR
.IP
IPv4 address of a remote machine.
.PP

.HP
\fIbus-id\fR
.IP
Bus ID of a local device to be connected.
.PP

.SH "SEE ALSO"
\fBusbip_ex_cmd_list_local\fP\fB(8)\fB\fP
\fBusbip_ex_cmd_disconnect\fP\fB(8)\fB\fP
