.TH USBIP "8" "May 2016" "usbip" "System Administration Utilities"
.SH NAME
usbip_ex_cmd_detach \- detaches USB device.
.SH SYNOPSIS
.B usbip_ex_cmd_detach
<\fIport-number\fR>

.SH DESCRIPTION
A USB/IP API example. Detaches a device which is shown by \fBport\fR command.

.SH OPTIONS
.HP
\fIport-number\fR
.IP
Port number of attached device.
.PP

.SH "SEE ALSO"
\fBusbip_ex_cmd_attach\fP\fB(8)\fB\fP
\fBusbip_ex_cmd_port\fP\fB(8)\fB\fP
