.TH USBIP "8" "May 2016" "usbip" "System Administration Utilities"
.SH NAME
usbip_ex_cmd_port \- lists attahced USB device.
.SH SYNOPSIS
.B usbip_ex_cmd_detach
<\fIport-number\fR>

.SH DESCRIPTION
A USB/IP API example. Lists devices which are imported by \fBattach\fR command.

.SH "SEE ALSO"
\fBusbip_ex_cmd_attach\fP\fB(8)\fB\fP
